<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Dabomase.ItalianDateTimeUtils</AssemblyName>
    <Version>1.2.0</Version>
    <PackageReleaseNotes>Add newly introduced Saint Francis of Assisi public national holiday (Oct 4th), starting from 2026.</PackageReleaseNotes>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Description>Simple and pluggable utilities library that aims to help Italian developers or any developer who needs support when dealing with Italian holidays and work days calculations.</Description>
    <Authors>Davide Borghi (@davideborghi), Massimo Serra (@massimo93)</Authors>
    <PackageProjectUrl>https://github.com/massimo93/dabomase-italian-datetime-utils</PackageProjectUrl>
    <RequireLicenseAcceptance>true</RequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Copyright © 2025 Davide Borghi and Massimo Serra</Copyright>
    <PackageTags>Italian ItalianCommunity DateTime DateTimeUtils ItalianDateTime NetStandard2.0 ItalianHolidays ItalianWorkdays</PackageTags>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\..\CHANGELOG.md" Pack="true" PackagePath="" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>
  
</Project>