<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseNuGetPackage>true</UseNuGetPackage>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseNuGetPackage)' == 'true'">
        <!-- Reference the NuGet package -->
        <PackageReference Include="Dabomase.ItalianDateTimeUtils" Version="1.2.0" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseNuGetPackage)' != 'true'">
        <!-- Reference the local project -->
        <ProjectReference Include="..\..\src\Dabomase.ItalianDateTimeUtils\Dabomase.ItalianDateTimeUtils.csproj" />
    </ItemGroup>

</Project>
